name: Workflow github actions 

on:
  push:
    branches: [main]
  schedule:
    - cron: '30 */2 * * *'  # Run every 2 hours offset by 30 minutes

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run:
          op_2.py
